name: VillagerShop
main: me.NinetyNine.villagershop.VillagerShop
version: 1.0
depend: [Vault, AutoSell]
description: An ability merchant plugin
commands:
  ability:
    usage: /<command>

  aability:
    usage: /<command>
    permission: ability.admin
permissions:
  ability.admin:
    default: op